### ISSUE TITLE
Does not appear to pulling data. 

### ISSUE THREAD

**Issue by andrewchumchal** [kdeyev/eyeonwater#8] opened 2022-11-15 22:48 UTC
I just install the integration today and this is what I'm getting in my error log.

![image](https://user-images.githubusercontent.com/8008169/202040994-36a1b429-b9d7-423e-a095-a5a26b2b8c55.png)

Here is my device setting

![image](https://user-images.githubusercontent.com/8008169/202041113-9083f2f6-b47c-410b-b8f4-4f2d6468b23f.png)

**Comment by kdeyev** [comment] 2022-11-15 23:01
I've just pushed a fix.
Please update and verify if it works now.

**Comment by andrewchumchal** [comment] 2022-11-16 01:51
It appears the calculation is off. It's like it's times it 100 

![image](https://user-images.githubusercontent.com/8008169/202063672-49a4eb11-3eb8-4ef1-afcd-5b9fd1c5d00a.png)

and i think it needs to / by 100 
![image](https://user-images.githubusercontent.com/8008169/202063724-ed90af14-744c-44f3-83ec-df03e7eba124.png)

**Comment by kdeyev** [comment] 2022-11-16 01:56
Everything looks correct: 149.242 (100 GAL) is equal to 14924.2 (GAL). 
Home assistant does not understand "100 GAL" measurement unit, I think EOW invention :-)

**Comment by andrewchumchal** [comment] 2022-11-16 01:59
I summited a PR that fix the issue on my side. I don't believe there needs to be any math involved. The meter that is install is brand new and I'm sure there not 14,000 gallons though it

![image](https://user-images.githubusercontent.com/8008169/202064588-ab995e07-9ea4-4b2c-841f-d5fd855b1564.png)

**Comment by kdeyev** [comment] 2022-11-16 02:05
I don't mind to approve the PR if everything works for you and I see your point. 
But I think that the problem is in the EOW side: they report the measurement unit is "100 GAL".
Could you please double check that the numbers on your meter are in gallons and not in hundreds of gallons?

**Comment by kdeyev** [comment] 2022-11-16 02:08
@andrewchumchal  The simplest way to check it - take a look at your daily water consumption. 
It cannot be 2-4 gallons per day :-)

**Comment by kdeyev** [comment] 2022-11-16 02:18
@johnwarne 
It was a stupid bug I introduced today.
I just fixed it. Please update once again. 
And thank you for reporting the issue

**Closed** 2022-11-16 02:51 UTC

**Comment by caliKev** [comment] 2022-11-16 23:02
Thanks so much for this integration. I almost have it working. Sorry I can’t help you on issue #2. I have a very similar error to the one described above with the exception the unit CCF. 

`
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/eyeonwater/sensor.py", line 85, in _state_update
    self._state = self.meter.reading
  File "/config/custom_components/eyeonwater/eow.py", line 152, in reading
    raise EyeOnWaterAPIError(f"Unsupported measurement unit: {read_unit}")
custom_components.eyeonwater.eow.EyeOnWaterAPIError: Unsupported measurement unit: CCF `

**Comment by kdeyev** [comment] 2022-11-16 23:14
@caliKev I've just added support for CCF, it will be converted to gallons.
Please update and verify.

**Comment by caliKev** [comment] 2022-11-17 18:07
@kdeyev Thanks so much for the quick fix. The sensor has a value now. My system only uploads one reading daily, hopefully energy meter starts working once there is a second reading.
